-- ============================================================
-- Emerald Frinters - PostgreSQL Database Schema
-- Generated from EF Core Migration: InitialPostgreSQLMigration
-- Database: logistics_db
-- ============================================================

-- Create database (run separately as superuser if needed)
-- CREATE DATABASE logistics_db;
-- CREATE USER logistics_user WITH PASSWORD 'your_password';
-- GRANT ALL PRIVILEGES ON DATABASE logistics_db TO logistics_user;

-- ============================================================
-- ENUM REFERENCE (stored as integers in the database)
-- ============================================================
-- UserRole:       0=Customer, 1=Admin, 2=Staff
-- ShipmentStatus: 0=Pending, 1=PickedUp, 2=InTransit, 3=OutForDelivery, 4=Delivered, 5=Cancelled
-- ServiceType:    0=Standard, 1=Express, 2=Overnight, 3=SeaFreightFCL, 4=SeaFreightLCL, 5=AirFreight, 6=LandTransport
-- InvoiceStatus:  0=Draft, 1=Sent, 2=Paid, 3=Overdue, 4=Cancelled
-- DocumentType:   0=Label, 1=Invoice, 2=Customs, 3=POD

-- ============================================================
-- TABLES
-- ============================================================

-- 1. Users
CREATE TABLE "Users" (
    "Id"                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email"                   CHARACTER VARYING(255) NOT NULL,
    "PasswordHash"            TEXT NOT NULL,
    "FirstName"               CHARACTER VARYING(100) NOT NULL,
    "LastName"                CHARACTER VARYING(100) NOT NULL,
    "PhoneNumber"             TEXT,
    "Role"                    INTEGER NOT NULL,
    "IsActive"                BOOLEAN NOT NULL,
    "FailedLoginAttempts"     INTEGER NOT NULL,
    "LockoutUntil"            TIMESTAMP WITH TIME ZONE,
    "PasswordResetToken"      TEXT,
    "PasswordResetTokenExpiry" TIMESTAMP WITH TIME ZONE,
    "CreatedAt"               TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt"               TIMESTAMP WITH TIME ZONE
);

-- 2. Customers
CREATE TABLE "Customers" (
    "Id"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"          INTEGER NOT NULL,
    "Name"            TEXT NOT NULL,
    "Email"           TEXT NOT NULL,
    "Phone"           TEXT NOT NULL,
    "Address"         TEXT,
    "City"            TEXT,
    "CompanyName"     TEXT,
    "TaxId"           TEXT,
    "BillingAddress"  TEXT,
    "ShippingAddress" TEXT,
    "CreditLimit"     NUMERIC NOT NULL,
    "CurrentBalance"  NUMERIC NOT NULL,
    "CreatedAt"       TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt"       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT "FK_Customers_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- 3. Shipments
CREATE TABLE "Shipments" (
    "Id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TrackingNumber"        CHARACTER VARYING(50) NOT NULL,
    "CustomerId"            INTEGER NOT NULL,
    "OriginAddress"         TEXT NOT NULL,
    "OriginCity"            TEXT NOT NULL,
    "OriginState"           TEXT NOT NULL,
    "OriginZipCode"         TEXT NOT NULL,
    "DestinationAddress"    TEXT NOT NULL,
    "DestinationCity"       TEXT NOT NULL,
    "DestinationState"      TEXT NOT NULL,
    "DestinationZipCode"    TEXT NOT NULL,
    "Status"                INTEGER NOT NULL,
    "Weight"                NUMERIC NOT NULL,
    "Distance"              NUMERIC,
    "ServiceType"           INTEGER NOT NULL,
    "EstimatedDeliveryDate" TIMESTAMP WITH TIME ZONE,
    "ActualDeliveryDate"    TIMESTAMP WITH TIME ZONE,
    "SpecialInstructions"   TEXT,
    "CreatedAt"             TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt"             TIMESTAMP WITH TIME ZONE,
    CONSTRAINT "FK_Shipments_Customers_CustomerId"
        FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT
);

-- 4. Packages
CREATE TABLE "Packages" (
    "Id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ShipmentId"  INTEGER NOT NULL,
    "Weight"      NUMERIC NOT NULL,
    "Length"      NUMERIC NOT NULL,
    "Width"       NUMERIC NOT NULL,
    "Height"      NUMERIC NOT NULL,
    "Description" TEXT,
    CONSTRAINT "FK_Packages_Shipments_ShipmentId"
        FOREIGN KEY ("ShipmentId") REFERENCES "Shipments" ("Id") ON DELETE CASCADE
);

-- 5. TrackingEvents
CREATE TABLE "TrackingEvents" (
    "Id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ShipmentId"  INTEGER NOT NULL,
    "Status"      INTEGER NOT NULL,
    "Location"    TEXT,
    "Description" TEXT,
    "EventDate"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy"   INTEGER,
    CONSTRAINT "FK_TrackingEvents_Shipments_ShipmentId"
        FOREIGN KEY ("ShipmentId") REFERENCES "Shipments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TrackingEvents_Users_CreatedBy"
        FOREIGN KEY ("CreatedBy") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

-- 6. Invoices
CREATE TABLE "Invoices" (
    "Id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InvoiceNumber" CHARACTER VARYING(50) NOT NULL,
    "CustomerId"    INTEGER NOT NULL,
    "IssueDate"     TIMESTAMP WITH TIME ZONE NOT NULL,
    "DueDate"       TIMESTAMP WITH TIME ZONE NOT NULL,
    "SubTotal"      NUMERIC NOT NULL,
    "TaxAmount"     NUMERIC NOT NULL,
    "TotalAmount"   NUMERIC NOT NULL,
    "Status"        INTEGER NOT NULL,
    "PaidDate"      TIMESTAMP WITH TIME ZONE,
    "PaymentMethod" TEXT,
    "Notes"         TEXT,
    CONSTRAINT "FK_Invoices_Customers_CustomerId"
        FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT
);

-- 7. InvoiceLineItems
CREATE TABLE "InvoiceLineItems" (
    "Id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InvoiceId"   INTEGER NOT NULL,
    "ShipmentId"  INTEGER NOT NULL,
    "Description" TEXT NOT NULL,
    "Quantity"    INTEGER NOT NULL,
    "UnitPrice"   NUMERIC NOT NULL,
    "Amount"      NUMERIC NOT NULL,
    CONSTRAINT "FK_InvoiceLineItems_Invoices_InvoiceId"
        FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InvoiceLineItems_Shipments_ShipmentId"
        FOREIGN KEY ("ShipmentId") REFERENCES "Shipments" ("Id") ON DELETE RESTRICT
);

-- 8. PricingRules
CREATE TABLE "PricingRules" (
    "Id"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServiceType"       INTEGER NOT NULL,
    "BaseRate"          NUMERIC NOT NULL,
    "WeightRatePerKg"   NUMERIC NOT NULL,
    "DistanceRatePerKm" NUMERIC NOT NULL,
    "MinimumCharge"     NUMERIC NOT NULL,
    "IsActive"          BOOLEAN NOT NULL,
    "EffectiveFrom"     TIMESTAMP WITH TIME ZONE NOT NULL,
    "EffectiveTo"       TIMESTAMP WITH TIME ZONE
);

-- 9. Documents
CREATE TABLE "Documents" (
    "Id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ShipmentId"   INTEGER NOT NULL,
    "DocumentType" INTEGER NOT NULL,
    "FileName"     TEXT NOT NULL,
    "FilePath"     TEXT NOT NULL,
    "FileSize"     BIGINT,
    "UploadedAt"   TIMESTAMP WITH TIME ZONE NOT NULL,
    "UploadedBy"   INTEGER,
    CONSTRAINT "FK_Documents_Shipments_ShipmentId"
        FOREIGN KEY ("ShipmentId") REFERENCES "Shipments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Documents_Users_UploadedBy"
        FOREIGN KEY ("UploadedBy") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

-- 10. ContactForms
CREATE TABLE "ContactForms" (
    "ContactFormId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          CHARACTER VARYING(200) NOT NULL,
    "Email"         CHARACTER VARYING(255) NOT NULL,
    "Phone"         TEXT,
    "Subject"       CHARACTER VARYING(200) NOT NULL,
    "Message"       TEXT NOT NULL,
    "CreatedAt"     TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 11. Quotes
CREATE TABLE "Quotes" (
    "Id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuoteNumber"   CHARACTER VARYING(50) NOT NULL,
    "Origin"        CHARACTER VARYING(255) NOT NULL,
    "Destination"   CHARACTER VARYING(255) NOT NULL,
    "ServiceType"   INTEGER NOT NULL,
    "CargoType"     CHARACTER VARYING(100) NOT NULL,
    "Weight"        NUMERIC NOT NULL,
    "ContainerSize" TEXT,
    "Price"         NUMERIC NOT NULL,
    "Currency"      CHARACTER VARYING(10) NOT NULL,
    "EstimatedDays" INTEGER NOT NULL,
    "Distance"      NUMERIC NOT NULL,
    "IsBooked"      BOOLEAN NOT NULL,
    "CustomerId"    INTEGER,
    "CreatedAt"     TIMESTAMP WITH TIME ZONE NOT NULL,
    "BookedAt"      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT "FK_Quotes_Customers_CustomerId"
        FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE UNIQUE INDEX "IX_Users_Email"               ON "Users" ("Email");
CREATE UNIQUE INDEX "IX_Customers_UserId"           ON "Customers" ("UserId");
CREATE UNIQUE INDEX "IX_Shipments_TrackingNumber"   ON "Shipments" ("TrackingNumber");
CREATE        INDEX "IX_Shipments_CustomerId"       ON "Shipments" ("CustomerId");
CREATE        INDEX "IX_Packages_ShipmentId"        ON "Packages" ("ShipmentId");
CREATE        INDEX "IX_TrackingEvents_ShipmentId"  ON "TrackingEvents" ("ShipmentId");
CREATE        INDEX "IX_TrackingEvents_CreatedBy"   ON "TrackingEvents" ("CreatedBy");
CREATE UNIQUE INDEX "IX_Invoices_InvoiceNumber"     ON "Invoices" ("InvoiceNumber");
CREATE        INDEX "IX_Invoices_CustomerId"        ON "Invoices" ("CustomerId");
CREATE        INDEX "IX_InvoiceLineItems_InvoiceId" ON "InvoiceLineItems" ("InvoiceId");
CREATE        INDEX "IX_InvoiceLineItems_ShipmentId" ON "InvoiceLineItems" ("ShipmentId");
CREATE        INDEX "IX_Documents_ShipmentId"       ON "Documents" ("ShipmentId");
CREATE        INDEX "IX_Documents_UploadedBy"       ON "Documents" ("UploadedBy");
CREATE UNIQUE INDEX "IX_Quotes_QuoteNumber"         ON "Quotes" ("QuoteNumber");
CREATE        INDEX "IX_Quotes_CustomerId"          ON "Quotes" ("CustomerId");

-- ============================================================
-- SEED DATA (Default Pricing Rules)
-- ============================================================

INSERT INTO "PricingRules" ("ServiceType", "BaseRate", "WeightRatePerKg", "DistanceRatePerKm", "MinimumCharge", "IsActive", "EffectiveFrom", "EffectiveTo")
VALUES
    (0, 10.00, 0.50, 0.10, 15.00, TRUE, NOW(), NULL),  -- Standard
    (1, 20.00, 1.00, 0.20, 30.00, TRUE, NOW(), NULL),  -- Express
    (2, 35.00, 1.50, 0.35, 50.00, TRUE, NOW(), NULL);  -- Overnight
